name: routepicker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.1
  location: ^5.0.0
  http: ^0.13.3
  geolocator: ^7.6.2
  geocoding: ^2.1.1
  flutter_polyline_points: ^1.0.0
  bloc: ^8.1.4
  equatable: ^2.0.0
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
